### ISSUE TITLE
Not an issue, SearchByProjection

### ISSUE THREAD

**Issue by leyuan-sun** [yepeichu123/orbslam2_learn#2]
Thank you for sharing the implementation of SearchByBow, do you have implementation about SearchByProjection? 

Anyway, thanks!

**Comment by yepeichu123** [comment]
> Thank you for sharing the implementation of SearchByBow, do you have implementation about SearchByProjection?
> 
> Anyway, thanks!

Hello, I have add the function MatchingByProject which you need. So you can update the code and read it. Enjoy yourself.
